/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import {Select} from '@react-three/postprocessing'


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Ghosts.glb')
  const [zombieHovered, setZombieHovered] = useState(null);
  const [demonHovered, setDemonHovered] = useState(null);
  const [gorillaHovered, setGorillaHovered] = useState(null);
  const [bearHovered, setBearHovered] = useState(null);
  return (
    <group ref={group} {...props} dispose={null}>
      <Select enabled={zombieHovered}>
      <group position={[32.13, 2.02, -14.68]} rotation={[0.06, -1.05, 0.06]} scale={1.31} onClick={props.handleModelClick} name='ZombieGhost' onPointerOver={() => setZombieHovered(true)} onPointerOut={() => setZombieHovered(false)}>
      <mesh geometry={nodes.mesh007.geometry} material={materials.Zombie} />
        <mesh geometry={nodes.mesh007_1.geometry} material={materials.ZombieBlood} />
        <mesh geometry={nodes.mesh007_2.geometry} material={materials['RedEyes.001']} />
        <mesh geometry={nodes.mesh007_3.geometry} material={materials.VBlack} />
        <mesh geometry={nodes.mesh007_4.geometry} material={materials.NameStone} />
        <mesh geometry={nodes.mesh007_5.geometry} material={materials.NameStoneName} />
      </group>
      </Select>
      <Select enabled={demonHovered}>
      <group position={[30.53, 1.88, -16.82]} rotation={[0, -0.81, 0]} scale={1.31} onClick={props.handleModelClick} name='DemonGhost' onPointerOver={() => setDemonHovered(true)} onPointerOut={() => setDemonHovered(false)}>
      <mesh geometry={nodes.mesh009.geometry} material={materials.Skull} />
        <mesh geometry={nodes.mesh009_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.mesh009_2.geometry} material={materials.GemRed} />
        <mesh geometry={nodes.mesh009_3.geometry} material={materials.GemGreen} />
        <mesh geometry={nodes.mesh009_4.geometry} material={materials.ZombieBlood} />
        <mesh geometry={nodes.mesh009_5.geometry} material={materials.VBlack} />
        <mesh geometry={nodes.mesh009_6.geometry} material={materials.BlackBody} />
        <mesh geometry={nodes.mesh009_7.geometry} material={materials.NameStone} />
        <mesh geometry={nodes.mesh009_8.geometry} material={materials.NameStoneName} />
        <mesh geometry={nodes.mesh009_9.geometry} material={materials.RedEyes} />
      </group>
      </Select>
      <Select enabled={gorillaHovered}>
      <group position={[30.56, 1.93, -15.69]} rotation={[0, -0.84, 0]} scale={1.31} onClick={props.handleModelClick} name = 'GorillaGhost' onPointerOver={() => setGorillaHovered(true)} onPointerOut={() => setGorillaHovered(false)}>
      <mesh geometry={nodes.mesh010.geometry} material={materials.Gorilla} />
        <mesh geometry={nodes.mesh010_1.geometry} material={materials.VBlack} />
        <mesh geometry={nodes.mesh010_2.geometry} material={materials.BlackBody} />
        <mesh geometry={nodes.mesh010_3.geometry} material={materials.NameStone} />
        <mesh geometry={nodes.mesh010_4.geometry} material={materials.NameStoneName} />
        <mesh geometry={nodes.mesh010_5.geometry} material={materials.RedEyes} />
      </group>
      </Select>
      <Select enabled={bearHovered}>
      <group position={[30.88, 1.95, -15.47]} rotation={[0, -0.89, 0]} scale={1.31} onClick={props.handleModelClick} name='BearGhost' onPointerOver={() => setBearHovered(true)} onPointerOut={() => setBearHovered(false)}>
      <mesh geometry={nodes.mesh011.geometry} material={materials.VBlack} />
        <mesh geometry={nodes.mesh011_1.geometry} material={materials.BlackBody} />
        <mesh geometry={nodes.mesh011_2.geometry} material={materials['Bear Blue']} />
        <mesh geometry={nodes.mesh011_3.geometry} material={materials.BearNose} />
        <mesh geometry={nodes.mesh011_4.geometry} material={materials.NearEye} />
        <mesh geometry={nodes.mesh011_5.geometry} material={materials.BearTeeth} />
        <mesh geometry={nodes.mesh011_6.geometry} material={materials.EyesWhite} />
        <mesh geometry={nodes.mesh011_7.geometry} material={materials.NameStone} />
        <mesh geometry={nodes.mesh011_8.geometry} material={materials.NameStoneName} />
      </group>
      </Select>
    </group>
  )
}

useGLTF.preload('/Ghosts.glb')
