/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import {Select} from '@react-three/postprocessing'

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/NFTSection.glb');
  const [guardianHovered, setGuardianHovered] = useState(null);
  const [genesisHovered, setGenesisHovered] = useState(null);
  const [moonPassHovered, setMoonPassHovered] = useState(null);
  return (
    <group ref={group} {...props} dispose={null}>
      <Select enabled={guardianHovered}>
        <group position={[-23.76, 8.67, -50.11]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} onClick={props.handleModelClick} name = 'Guardian Ghost NFTs' onPointerOver={() => setGuardianHovered(true)} onPointerOut={() => setGuardianHovered(false)}>
          <mesh geometry={nodes.Text.geometry} material={materials.GuardiansText} />
          <mesh geometry={nodes.Text_1.geometry} material={materials.ArtFrame} />
          <mesh geometry={nodes.Text_2.geometry} material={materials.Guardian4} />
          <mesh geometry={nodes.Text_3.geometry} material={materials.Guardian1} />
          <mesh geometry={nodes.Text_4.geometry} material={materials.Artwork} />
        </group>
      </Select>

      <Select enabled={genesisHovered}>
      <group position={[-8.12, 9.2, -59.94]} rotation={[Math.PI / 2, 0, 0]} onClick={props.handleModelClick} name = 'Genesis Ghost NFTs' onPointerOver={() => setGenesisHovered(true)} onPointerOut={() => setGenesisHovered(false)}>
        <mesh geometry={nodes.Text001.geometry} material={materials.GenesisText} />
        <mesh geometry={nodes.Text001_1.geometry} material={materials.ArtFrame} />
        <mesh geometry={nodes.Text001_2.geometry} material={materials.Genesis1} />
        <mesh geometry={nodes.Text001_3.geometry} material={materials.Genesis2} />
        <mesh geometry={nodes.Text001_4.geometry} material={materials.Genesis3} />
        <mesh geometry={nodes.Text001_5.geometry} material={materials.Artwork} />
      </group>
      </Select>

      <Select enabled={moonPassHovered}>
      <group position={[-23.76, 8.68, -38.62]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} onClick={props.handleModelClick} name = 'MoonPasses' onPointerOver={() => setMoonPassHovered(true)} onPointerOut={() => setMoonPassHovered(false)}>
        <mesh geometry={nodes.Text003.geometry} material={materials.MoonPassText} />
        <mesh geometry={nodes.Text003_1.geometry} material={materials.ArtFrame} />
        <mesh geometry={nodes.Text003_2.geometry} material={materials.MoonPassBasic} />
        <mesh geometry={nodes.Text003_3.geometry} material={materials.Artwork} />
      </group>
      </Select>
    </group>
  )
}

useGLTF.preload('/NFTSection.glb')
