/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import {Select} from '@react-three/postprocessing'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/RoadmapSection.glb')
  const [phase1Hovered, setPhase1Hovered] = useState(null);
  const [phase2Hovered, setPhase2Hovered] = useState(null);
  const [phase3Hovered, setPhase3Hovered] = useState(null);
  const [phase4Hovered, setPhase4Hovered] = useState(null);
  const [boatHovered, setBoatHovered] = useState(null);
  return (
    <group ref={group} {...props} dispose={null}>
      <Select enabled={phase3Hovered}>
      <group position={[34.01, 3.2, 46.6]} scale={1.82}>
        <mesh geometry={nodes.Sphere.geometry} material={materials.Roadmap1} onClick={props.handleModelClick} name = 'Phase 3' onPointerOver={() => setPhase3Hovered(true)} onPointerOut={() => setPhase3Hovered(false)} />
        <mesh geometry={nodes.Sphere_1.geometry} material={materials.Roadmap2} />
      </group>
      </Select>
      <Select enabled={phase2Hovered}>
      <group position={[39.16, 1.01, 44.97]} scale={1.82}>
        <mesh geometry={nodes.Sphere001.geometry} material={materials.Roadmap1} onClick={props.handleModelClick} name = 'Phase 2' onPointerOver={() => setPhase2Hovered(true)} onPointerOut={() => setPhase2Hovered(false)} />
        <mesh geometry={nodes.Sphere001_1.geometry} material={materials.Roadmap2} />
      </group>
      </Select>
      <Select enabled={phase1Hovered}>
      <group position={[43.53, -1.52, 41.83]} scale={1.82}>
        <mesh geometry={nodes.Sphere002.geometry} material={materials.Roadmap1} onClick={props.handleModelClick} name = 'Phase 1' onPointerOver={() => setPhase1Hovered(true)} onPointerOut={() => setPhase1Hovered(false)} />
        <mesh geometry={nodes.Sphere002_1.geometry} material={materials.Roadmap2} />
      </group>
      </Select>
      <Select enabled={phase4Hovered}>
      <group position={[29.15, 5.38, 47.67]} scale={1.82}>
        <mesh geometry={nodes.Sphere003.geometry} material={materials.Roadmap1} onClick={props.handleModelClick} name = 'Phase 4' onPointerOver={() => setPhase4Hovered(true)} onPointerOut={() => setPhase4Hovered(false)} />
        <mesh geometry={nodes.Sphere003_1.geometry} material={materials.Roadmap2} />
      </group>
      </Select>
      <Select enabled={boatHovered}>
      <group position={[0.15, 0.06, -0.08]} onClick={props.handleModelClick} name = 'Boat' onPointerOver={() => setBoatHovered(true)} onPointerOut={() => setBoatHovered(false)}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.Wood2} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.Wood1} />
      </group>
      </Select>
    </group>
  )
}

useGLTF.preload('/RoadmapSection.glb')
