/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import {Select} from '@react-three/postprocessing'


const discordLink = 'https://discord.gg/fJHbTxspDk';
const twitterLink = 'https://twitter.com/MoonGhostNFT';


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Socials.glb')

  const [discordHovered, setDiscordHovered] = useState(null);
  const [twitterHovered, setTwitterHovered] = useState(null);

  const openInNewTab = (url) => {
    const newWindow = window.open(url, '_blank', 'noopener,noreferrer')
    if (newWindow) newWindow.opener = null}
  return (
    <group ref={group} {...props} dispose={null}>
      <Select enabled={discordHovered}>
      <mesh geometry={nodes.DiscordLogo001.geometry} material={materials.DiscordLogo} onClick={() => openInNewTab(discordLink)}
      onPointerOver={() => setDiscordHovered(true)} onPointerOut={() => setDiscordHovered(false)}/>
      </Select>
      <Select enabled={twitterHovered}>
      <mesh geometry={nodes.Twitter.geometry} material={materials['15 - Default']} position={[-11.15, 0.27, 3.74]} onClick={() => openInNewTab(twitterLink)} 
      onPointerOver={() => setTwitterHovered(true)} onPointerOut={() => setTwitterHovered(false)}/>
      </Select>
    </group>
  )
}

useGLTF.preload('/Socials.glb')
