/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import {Select} from '@react-three/postprocessing'


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/StartSection.glb')

  const [debrisHovered, setDebrisHovered] = useState(null);

  return (
    <group ref={group} {...props} dispose={null}>
      <Select enabled={debrisHovered}>
      <group position={[-26.07, 3.38, 2.25]} rotation={[0.78, 0.13, -1.08]} scale={[9.59, 11.02, 11.02]} onClick={props.handleModelClick} name = 'Debris'
      onPointerOver={() => setDebrisHovered(true)} onPointerOut={() => setDebrisHovered(false)} >
        <mesh geometry={nodes.Text002.geometry} material={materials.MoonGhostTitle} />
        <mesh geometry={nodes.Text002_1.geometry} material={materials.MGLogo} />
        <mesh geometry={nodes.Text002_2.geometry} material={materials['Material.057']} />
      </group>
      </Select>
      <group position={[-11.07, 1.44, 4.31]} rotation={[0, 0.33, 0]} scale={[0.09, 1.53, 1.53]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.Billboard} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Wood3} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Wood2} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.MoonGhostBillboard} />
      </group>
    </group>
  )
}

useGLTF.preload('/StartSection.glb')
